[package]
name = "merkle_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_merkle = "1.2"
sha3 = "0.10.2"
hex = "0.4.3"